### ISSUE TITLE
Upgrade issue (2.3.7 to 2.3.8) / unable to start z-way-server

### ISSUE THREAD

**Issue by kovi44** [Z-Wave-Me/z-way-issues#144]
Hi,

I got RPI3 with raspbian jessie (fully up-to-date). I tried the upgrade from 2.3.7 to 2.3.8 several times, but it always failed. 

Any kind of help more then welcome. 

The log output 

/var/log/z-way-server.log
[2018-11-04 10:14:03.276] [core] Executing script: /*** Z-Way Home Automation Engine main executable ***************************** ...
[2018-11-04 10:14:03.279] [core] Executing script: // Comon utilities and functions ...
[2018-11-04 10:14:03.290] [core] Executing script: // This script transforms old formats to new ...
[2018-11-04 10:14:03.758] [E] [core] result: Error: SyntaxError: Unexpected end of input
at automation/main.js:31:11
at Array.filter (native)
at automation/main.js:30:37

What can be wrong??

**Comment by PoltoS** [comment]
Check your automation/storage/config.json-... file. It looks to be corrupted

**Comment by kovi44** [comment]
I don’t really understand. In 2.3.7 my config file working fine, in 2.3.8 not. How I can find and fix the issue without doing the fresh install of 2.3.8 
Please understand that I got more then 100 http devices, lot of ifs, condtitions, trigers,..

I really would love to find the way how to find the issue with storage/configjson file. 

Thanks
Really appreciate your help

**Comment by ronie-z-wave** [comment]
Hi,

sry for the late response.

Please try this fix: https://github.com/Z-Wave-Me/home-automation/commit/2a669e74e6210b9963a659c107c571d152f689d2

I had a broken file within the storage (zwayrssidata) which was cut - I've no idea why.
And because the loadObject() was not surrounded by an error handler it's parser throws an error exception and the start of z-way-server failed.

BR Niels
