### ISSUE TITLE
Polling of non-association switches

### ISSUE THREAD

**Issue by jhmartin** [Z-Wave-Me/z-way-issues#43]
GE/Jasco wall switches unfortunately do not support associations.  This means that automation such as AutoOff does not work if the switch is turned on physically.  Some mechanism to poll the status of the switches is needed so that the dashboard and automation function properly.

**Comment by PoltoS** [comment]
Polling should be outside of Z-Way code and should be implemented as a Java Script add-on, since it is device/customer specific.

You can define polling separately using a special module in Home automation or via JS one line code like
setInterval(function() { zway.devices[N].SwitchBinary.Get(); }, 5_60_1000);

Do these devices support Hail CC? If so, latest version (rc25) should poll them automatically on Hail command from GE/Jasco.

**Comment by jhmartin** [comment]
Thank you for the quick response.  I'll look at that JS.   How can I determine if Hail CC is supported on the switches?

**Comment by PoltoS** [comment]
just look in the list of supported command classes in Expert UI in Interview tab. It should also be mentioned in the manual

**Comment by jhmartin** [comment]
Command classes listed are Basic, SwitchBinary, SwitchAll, Configuration, ManufacturerSpecific, PowerLevel, NodeNaming, Version, so I am guessing not.   The manual at http://jascoproducts.com/sites/default/files/product/manuals/12722%20EnFrSp%20QStart%20V1%20081814.pdf is entirely useless as to the ZWave parameters, so I'll keep looking for a definition somewhere or go the js polling route.

**Comment by jhmartin** [comment]
I just found https://github.com/jensmoes/Niffler which nicely works around the issue, at least when the NIFs reach the controller.

http://forum.z-wave.me/viewtopic.php?f=3424&t=20588 is a nice module that implements up to 60s polls.
