### ISSUE TITLE
EZ Motion 3-in-1 sensor - motion not reported

### ISSUE THREAD

**Issue by jverhoeven** [Z-Wave-Me/z-way-issues#52]
PoltoS mentioned in the forum that the coming release after 2.0.1 is going to about improving the z-way controller software. This item has been pending for quite some time.

The basic problem is that the EZ Motion sends a message to the gateway when motion is detected (structure 01 09 00 04 00 xx 03 20 01 yy, where xx=deviceid, yy=level), I see this in the log, but this is not shown in any of the GUIs and cannot be captured via dev.Basic.data.level.bind(function(type) {} or any other way but putting a tail on the log (which is what I am doing now).

As pofs replied in a post: "It is actually a pretty good question why it identifies as Multilevel sensor. And I don't have a reasonable answer to it."

Please see forum item http://forum.z-wave.me/viewtopic.php?f=3423&t=20926&start=10

**Comment by PoltoS** [comment]
This is a pretty old device using Channels to report different sensors. And for motion it does not send SensorBinary Report, but a Basic Set (means controls and not reports).

You can trap this event on devices[1].Basic.data.level (note that since it is not Report, but Set), it will be stored in ID 1 and not in this device's structure. srcNodeId will help to filter by incoming events sources.

You can also enable SwitchControlGenerator and it will trap this event and create a "control" widget. You can use it in logical rules and map to different devices (i.e. use BindDevices to map it to a dummy device)

**Comment by PoltoS** [comment]
Closed, since there is nothing to do except for those workarounds as the device do not honor some modern Z-Wave rules. But workaround will work perfectly!
