### ISSUE TITLE
Zway server stores plaintext passwords

### ISSUE THREAD

**Issue by maros** [Z-Wave-Me/z-way-issues#83]
automation/storage/configjson-XXX.json contains the plaintext user password. This is certainly not a good idea.

**Comment by PoltoS** [comment]
Well, we can use md5 with salt, but this is quite useless, since only admin can read it and edit id. And if you have access to the filesystem, you can anyway change the password by editing config.json.

Also md5 for most popular words are available in the network. This was reason to remove md5 from old version and use clean passwords only.

Same about the channel: it should use good encryption like WiFi WPA2 or SSL (like with find.z-wave.me).

Does it really make sense to store a hash?

**Comment by maros** [comment]
True, if you have access to the file then you can change the password - but that's not the reason for filing an issue here. I mainly have two concerns
- if i create a backup of the automation system then it would also contain the plaintext password. everybody with access to the backup files could login in the zway system 
- users tend to re-use one password for multiple systems. Everybody with access (even people with rightful access to the host running zway) a zway system could exploit this and try the passwords from other users against other services 

I agree that unsalted md5 passwords do not make a whole lot of sense. Instead I propose to store bcrypted passwords. There are plenty of JavaScript libraries for calculating bcrypt hashes (eg. https://github.com/nevins-b/javascript-bcrypt ).

Here's some pseudo-code how a bcrypt password check could look like:

```
constant currentCost = 10;
if (storedPassword matches '$2a$(\d+)$(.+)') {
    // Get cost from stored password
    storedCost = regexpMatch.1
    // Calculate hash for comparison
    calculatedHash = bcryptHash(userProvicedPassword,storedCost)
    // Check hash
    if (calculatedHash notequals storedPassword) {
        return HTTP_403
    }
    // Compare costs an re-calculate if cost constant was increased
    if (storedCost < currentCost) {
        hashedPassword = bcryptHash(userProvicedPassword,currentCost)
        storePassword(hashedPassword)
    }
    return HTTP_200
} else {
    // Password in plaintext (not yet bcrypted or manually reset by admin)
    if (userProvicedPassword equals userStoredPassword) {
        hashedPassword = bcryptHash(userProvicedPassword,currentCost)
        storePassword(hashedPassword)
        return HTTP_200
    } else {
        return HTTP_403
    }
}
```

**Comment by kvolden** [comment]
There's another reason why storing passwords in cleartext is a very bad idea. If someone gains temporary access to the file system, or finds a security issue that allows for configjson-XXX.json to leak, this person will now be able to log in to the system any time they please. If the password is stored in the form of a hash, they might get the hash, but they're not able to use that later for logging in through the normal interface. (Unless, of course, they brute force it, but that's why you need a good hashing algorithm.)

**Comment by pz1** [comment]
> There's another reason why storing passwords in cleartext is a very bad idea.

It is not only visisble in _configjson_'s user accounts, but also if your installation uses the app _Link other ZWay controller_

**Comment by PoltoS** [comment]
@pz1 May be good idea to make a pub/priv keys for this (make some access token). Anyway, this one will be stored in plain text, so will not increase level of security. There are no solutions for this except for protecting your filesystem.

**Comment by PoltoS** [comment]
@kvolden Re-posting my message from the forum:
As for passwords in config.json, I can not agree. Look on all Unix systems. Once you have access to /etc/shadow, you have all hashes and it is a matter of 10 minutes to get your password. Even more, having access to your filesystem one can install additional s/w and Z-Way is not to blame about this. This is same with all other systems where password is usually one word (this is the case for most user defined passwords). We have discussed this with the community a long time ago and found that storing passwords in hash is a perception of security which is even more severe.

**Comment by pz1** [comment]
> @pz1 May be good idea to make a pub/priv keys for this (make some access token)

That may indeed be worth to consider. At the time I installed _Link other Zway_ I wasn't aware it did store username/pasw. Took me a while before I discovered that a change of password caused the app to fail.

**Comment by PoltoS** [comment]
But keep in mind that you can use non-admin user for this. Make a special user. In that case it does not really differe from token

**Comment by kvolden** [comment]
@PoltoS It's not a matter of 10 minutes to get your password if the password and the hashing algorithm is good. Of course, if someone chooses "password123" as their password, it could be brute forced in seconds, but you can't assume that all users have such terrible password practice that this is the case. Many people **don't** have single word passwords that can be brute forced with a dictionary, When storing the password in cleartext, no matter the password entropy, security is still terribly lacking.

I mean, why would the Gnome Keyring – as a random example – iteratively hash the master password before storing it if what you said is right? It would be nonsense. And people would point out the nonsense. By storing the passwords strongly hashed, you would be doing things right, and if the user uses a terrible password, then that problem is on the shoulders of the user. At least you would have made it **possible** to have good security.

Although, I'm offering you to prove your point. The following is a password hashed with bcrypt, 12 rounds; can you find the password in 10 minutes?

$2a$12$U.oPgYm987AXaDKIHwgLcepb.yAatrwZfj5Fa/a/ilIs.VeyItnIa

**Comment by PoltoS** [comment]
Fixed with https://github.com/Z-Wave-Me/home-automation/commit/6bb553ce1e510a85e93ed1532b4171f275027897
