### ISSUE TITLE
I want to suppress "incomplete interview" warnings for devices with known CC bugs

### ISSUE THREAD

**Issue by geirgp** [Z-Wave-Me/z-way-issues#86]
On the "Interview" -page I want a (toggle?) button  "Suppress Incomplete Interview Warning", or something to that effect, which when enabled removes any "incomplete interview" error from the main page in the expert ui. 

The reason is simply that some devices will never complete the interview (incorrect supported cc advertisement, fw bugs..++) and this error on the main page is a big distraction/annoyance. It makes it harder for me to notice "real" incomplete interviews because there are so many "permanent"/unresolvable that I should ignore (counting 1 per qubino device.

**Comment by PoltoS** [comment]
wontfix

This contradicts with Z-Way way. Manufacturer should know about their problems from clients. Otherwise we (controller manufacturers) be between angry users and broken devices making hundreds of "fixes" and "hacks".

Hopefully Other-The-Air Upgrade available in most of 5th gen devices allows manufacturers to solve these problems.

To solve this we now have "postfix" feature and we add step by step devices in this postfix. But this will take time. This gives manufacturers time to solve their problems.
